# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Use PORT env var and root path
RUN sed -i "1iimport os" server.py \
    && sed -i "s/port=3001/port=int(os.environ.get('PORT','3001'))/" server.py \
    && sed -i "s/path=\"\/weather\"/path=\"\/\"/" server.py
EXPOSE 3001
CMD ["python", "server.py"]
